### ISSUE TITLE
Собранный пустой одминус возвращает 404 Not Found при добавлении агента

### ISSUE THREAD

**Issue by nixel2007** [EvilBeaver/odminus#11]
Собирал в докере, при добавлении агента:
![image](https://user-images.githubusercontent.com/1132840/48269624-9dce2800-e46a-11e8-9add-e2c0238cc075.png)

**Comment by anikin-v** [comment]
У меня то же самое без докера.

**Comment by EvilBeaver** [comment]
платформа свежая? Погляжу

**Comment by nixel2007** [comment]
в докере? из докерфайла с репой. onescript-web:dev

**Comment by anikin-v** [comment]
Если откатить последнее изменение, то все работает. В последнем изменении я не понял как должны вызываться методы ADD_POST() и ADD_GET()

**Comment by EvilBeaver** [comment]
ADD_POST и ADD_GET работают как фильтр Http-метода, которым клиент запросил страницу.

Работает (должно работать) так, как описано в этой задаче: https://github.com/EvilBeaver/OneScript.Web/issues/35

**Comment by EvilBeaver** [comment]
Нужна помощь в расследовании

**Comment by nixel2007** [comment]
А у тебя работает? @EvilBeaver?

**Comment by EvilBeaver** [comment]
Я еще не смотрел

**Comment by EvilBeaver** [comment]
На ветке develop не воспроизводится. Обновил докер-образ и настроил триггеры на сборку докер-образа.
