### ISSUE TITLE
Тип не зарегистрирован (АдминистрированиеКластера)

### ISSUE THREAD

**Issue by yakovsudarushkin** [EvilBeaver/odminus#16]
Добрый день.
Направьте, пожалуйста, куда смотреть.
**Не могу понять про какой тип мне ругается система?**

Есть windows сервер. есть служба 1с сервера, есть сервер ras.
Утилитой rac в консоли удается получать данные из ras. 
![image](https://user-images.githubusercontent.com/46089325/131264789-fde0f154-6a4e-4b9b-b34d-6eb43916d33e.png)

Запустил odminus локально на этом же сервере.
В веб морду зашел.
Добавил свой сервер как localhost (порт 1541) в список.
Проваливаюсь внутрь - вижу ошибку.

Ошибка выглядит так:

![image](https://user-images.githubusercontent.com/46089325/131264771-8b1bb077-1953-4387-be5b-71ac70f3a196.png)

An unhandled exception occurred while processing the request.

RuntimeException: {Модуль / Ошибка в строке: -1 / Тип не зарегистрирован (АдминистрированиеКластера)} 

ScriptEngine.Machine.StandartTypeManager.GetTypeByName(string name)

RuntimeException: {Модуль C:\Odminus\odminus\src\models\modules\ОбщегоНазначения.os / Ошибка в строке: 63 / Конструктор не найден (АдминистрированиеКластера)} 
Администрирование = Новый АдминистрированиеКластера(

ScriptEngine.Machine.TypeManager.GetFactoryFor(string typeName)
 Stack 
  Query 
  Cookies 
  Headers 
  Routing 
 

RuntimeException: {Модуль / Ошибка в строке: -1 / Тип не зарегистрирован (АдминистрированиеКластера)} 

ScriptEngine.Machine.StandartTypeManager.GetTypeByName(string name)

ScriptEngine.Machine.TypeManager.GetFactoryFor(string typeName)

**Comment by yakovsudarushkin** [comment]
Похоже я понял.
Как то вышло, что в библиотеке irac нет класса.

![image](https://user-images.githubusercontent.com/46089325/131265242-4ee0ad92-4cfd-4012-9fba-e5abede80c3d.png)

**Comment by yakovsudarushkin** [comment]
Похоже я понял.

В odminus используется старая версия библиотеки irac
https://github.com/arkuznetsov/irac/commit/68c38de6346517890759506042fc82418277aea9

Класс АдминистрированиеКластера устарел.
Теперь используется УправлениеКластером1С

**Comment by yakovsudarushkin** [comment]
Переопределил вызов класса с АдминистрированиеКластера на УправлениеКластером1С и заработало.
Вопрос закрыт

Функция ПолучитьАдминистрированиеКластера(Знач СетевоеИмя, Знач Порт, Знач Версия1С = "8.3") Экспорт
	
	Администрирование = Новый УправлениеКластером1С(
		Версия1С,
		СтрШаблон("%1:%2", СетевоеИмя, Порт)
	);
	Администрирование.УстановитьОбработчикОшибокКоманд(Новый ОбработчикОшибокRAC());

Возврат Администрирование;

КонецФункции

**Comment by EvilBeaver** [comment]
odminus заброшен и давно не дорабатывается. Нет ресурсов. Если кто-то за него возьмется - будет здорово, я дам доступ к репе на запись.

**Comment by yakovsudarushkin** [comment]
> odminus заброшен и давно не дорабатывается. Нет ресурсов. Если кто-то за него возьмется - будет здорово, я дам доступ к репе на запись.

Мне интересно это направление.
Надеюсь на Вашу небольшую методическую поддержку, если потребуется.

Сделал несколько правок. 
Как разберусь с GIT - напомню о себе.

Сначала хотя бы обработаю все ошибки имеющегося функционала. Разберусь получше в синтаксисе и общих механизмах.

**Comment by EvilBeaver** [comment]
Хорошо. Пишите лучше сразу в телегу: https://t.me/oscript_library будет быстрее
